### ISSUE TITLE
Plotly react-chart-editor for visualizations?

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/project#104]
We were able to prototype embedding Plotly's [react-chart-editor](https://www.npmjs.com/package/react-chart-editor) library in discovery-ui: 

We still need to answer the following questions: 
- How much data can it handle?
- How difficult is it to customize the editor pane?
- Can we tweak the CSS?

**Comment by abrock-accenture** [comment]
How much data can it handle?

Plotly limits their chart builder instance to 5k records per page. This seems to maintain performance and is a good sane default for us.

**Comment by abrock-accenture** [comment]
CSS can be tweaked by overriding the colors, fonts, etc. in a custom theme css file: https://github.com/plotly/react-chart-editor/blob/master/THEMING.md

This does not work with scss out of the box, but we could investigate further if we think it's worth pursuing.

**Comment by abrock-accenture** [comment]
How difficult is it to customize the editor pane?

Custom components can be substituted for the ones that come with the library. In addition, components can be added or disabled though it gets significantly more difficult the deeper into the editor you go.

**Comment by abrock-accenture** [comment]
Another question - who is the expected user of this tool?

The tool is very powerful, but is not necessarily intuitive.  We have found that the data needs to be in a very specific format for the user to be able to create a meaningful visualization.  For most of the data we have, it's pretty difficult to just dump raw data into the tool and explore it.  The user will likely need to have some understanding of how to query the data to see the kinds of information that can be easily charted, i.e. grouping, counting, summing, averaging fields in the query.  The transformation/aggregation tools in the chart editor are pretty limited.
