### ISSUE TITLE
Static code analysis for Phoenix (Sobelow)

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/project#34]
"AS an OS developer,
 I WANT to build security into our development and deployment processes,
 SO THAT security vulnerabilities are addressed each time we update the OS software.

Acceptance Criteria:
 * Implement Continuously Integrated code analysis tool for all phoenix apps which performs checks for things like
 ** Insecure configuration
 ** Cross-Site Scripting
 ** SQL injection
 ** Command injection
 ** Code execution
 ** Directory traversal
 ** Unsafe serialization
 * Configuration of new security checks can be pulled in automatically (e.g. the library can be pulled in as latest)
 * Write cards to fix any problems and enable automatic build failing when complete.

Technical Notes:
 * Andi, Discovery-Streams and Discovery-api
 * It would be optimal if this tool was configurable to opt in or out of specific checks.

 

Note, this came from the pre-groomed list of cards, from meetings with Warner, Johnson, Jessie, Ben B and Rob.

06-24-19: Migrated from SMRT-1341"

**Comment by rob-h-m** [comment]
Duplicate of a card completed before migration - closing
