### ISSUE TITLE
Define process to update Elixir, Erlang as needed (and update them)

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/project#35]
"AS Andy the SCOS System Administrator,
 I WANT to keep all components of the Operating System up to date,
 SO THAT any security vulnerabilities that arise are patched before they expose the system to risk.

Acceptance Criteria:
 * Verify if there are any known security risks with our existing versions of Erlang, Elixir
 * If there are necessary security patches which should be applied, apply these to discovery-api.
 * Document the process on how to determine how, where, and when to update a core framework version.
 * Validate this process with Warner.
 * Write cards to perform these updates on other applications as necessary. 

Note, this came from the pre-groomed list of cards, from meetings with Warner, Johnson, Jessie, Ben B and Rob.

06-24-19: Migrated from SMRT-1334"

**Comment by jmorris-pillar** [comment]
Closing as this introduces more risk than it could prevent.  Approved for closing by Warner Moore
