### ISSUE TITLE
Open Source Test Generator App

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/project#37]
"As a developer implementing the Smart Cities data platform, I want an easy way to test against a data generating service.

Acceptance Criteria:
* The TDG App is open sourced
  * Readme and documented
  * Licensed properly  

Technical Notes:
* Not to be confused with the TDG library

06-24-19: Migrated from SMRT-1386"

**Comment by rob-h-m** [comment]
Moved to SCOS
