### ISSUE TITLE
Only act on ingest sourceTypes

### ISSUE THREAD

**Issue by jdenen** [smartcitiesdata/project#67]
We don't want to create topics for remote or host `sourceType` datasets. Previously, we had logic to create topics for sourceTypes implicitly. We'll switch it to an explicit model with this card.

Acceptance criteria:
- [ ] Create topics for `ingest` or `stream` sourceTypes
- [ ] streisand and genesis should only care about stream sourceTypes
- [ ] discovery-api completeness scoring continues to work as expected

**Comment by ManApart** [comment]
```
 # BEFORE ----------------------------------------------------------------------------
  def handle_dataset(%Dataset{technical: %{sourceType: "remote"}}) do
    :ok
  end

  def handle_dataset(%Dataset{} = dataset) do
    subscribe(dataset)
  end

  # AFTER ----------------------------------------------------------------------------
  def handle_dataset(%Dataset{technical: %{sourceType: "ingest"}} = dataset), do: subscribe(dataset)
  def handle_dataset(%Dataset{technical: %{sourceType: "stream"}} = dataset), do: subscribe(dataset)
  def handle_dataset(%Dataset{} = _dataset), do: :ok

```

**Comment by ManApart** [comment]
Will need to go to prod along with the [other issue](https://github.com/smartcitiesdata/reaper/issues/89)

**Comment by ManApart** [comment]
reaper
forklift
voltron
carpenter


People:
- Rob
- Johnson
- Mackenzie
- Jessie
- Jeff
- Jarred

Go To Prod
- Update all redis from batch to ingest
- Deploy Apps
- Check busses on a map
- Check a batch > ingest type?
